### ISSUE TITLE
HoleShapeMask doesn't fit the image

### ISSUE THREAD

**Issue by JHeisecke** [Rillieux/PhotoSelectAndCrop#3]
When the image is to long horizontally or vertically the HoleShapeMask doesn't fit the photo, therefore, when cropping the result image is not a circle.

To fix the issue on vertically long photos change the if to call `resetImageOriginScale()` to OR
```
if displayW < diameter - inset || displayH < diameter - inset {
    resetImageOriginAndScale()
}
```
But this doesn't solve the horizontally long photos
[Example](https://imgur.com/a/Wq5QvLV)

**Comment by Rillieux** [comment]
"You're holding it wrong" :) Just kidding. While this is an issue, the intent was that the user see the entire image selected and then be able to scale and move it.

For example, if a really tall and narrow image is chosen, then making it fill the cutout might leave a part of the image in the centre that is difficult to interpret contextually. If the entire image is visible, then the user can easily scale and move to crop the desired portion. 

Also, this is the same user experience as in Apple's own Contacts App, which is what we are trying to follow. So, I'll close this isssue.

Thank you for the interest and critique however!

**Comment by Rillieux** [comment]
Non-issue as this is the intended UX.

**Comment by JHeisecke** [comment]
Thanks for the response, but if it doesn't crop like the contacts app does, the contacts app will always crop a circle while your app (in this case mention above) will crop like a rectangle with round corners
